# job: start once, runs until completion
apiVersion: batch/v1 
kind: Job 
metadata:
  name: test-job 
spec: 
  completions: 3
  template:
    spec:
      containers:
      - name: hello
        image: busybox
        args: 
        - /bin/echo 
        - "Hello World"
      restartPolicy: OnFailure
