version: '3'
services:
  filehandling:
    build:
      context: .
      dockerfile: FileHandling.dockerfile
    environment:
      - PUBLIC_KEY_BUCKET=internal-keys
      - PUBLIC_KEY_LOCATION=public2.pem
    ports:
      - "3000:3000"
    networks:
      - default

networks:
  default: