version: '3'
services:
  user:
    build:
      context: .
      dockerfile: User.dockerfile
    environment:
      - PORT=3000
    ports:
      - "3000:3000"
    networks:
      - default
    volumes:
      - ./keys/:/work/keys/
  challenge:
    build:
      context: .
      dockerfile: Challenge.dockerfile
    environment:
      - PORT=3001
    ports:
      - "3001:3001"
    networks:
      - default
    volumes:
      - ./keys/:/work/keys/
  solution:
    build:
      context: .
      dockerfile: Solution.dockerfile
    environment:
      - PORT=3002
    ports:
      - "3002:3002"
    networks:
      - default
    volumes:
      - ./keys/:/work/keys/
  filehandling:
    build:
      context: .
      dockerfile: FileHandling.dockerfile
    environment:
      - PORT=3003
    ports:
      - "3003:3003"
    networks:
      - default
    volumes:
      - ./keys/:/work/keys/

networks:
  default: