
apiVersion: v1
kind: Service
metadata:
  name: challenge-service
  namespace: challenge
spec:
  selector:
    app: challenge
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer