
apiVersion: v1
kind: Service
metadata:
  name: filehandling-service
  namespace: filehandling
spec:
  selector:
    app: file-handling
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
