apiVersion: apps/v1
kind: Deployment
metadata:
  name: solution
  namespace: solution
  labels:
    app: solution

spec:
  replicas: 1
  selector:
    matchLabels:
      app: solution
  template:
    metadata:
      labels:
        app: solution
      namespace: solution
    spec:
      serviceAccountName: solution
      nodeSelector:
        iam.gke.io/gke-metadata-server-enabled: "true"
      containers:
        - name: solution
          image: europe-west4-docker.pkg.dev/codehub-400314/code-hub-main/solution:latest
          resources:
            limits:
              cpu: "1"
              memory: "512Mi"
            requests:
              cpu: "500m"
              memory: "256Mi"
          env:
            - name: SECRET_FILE_NAME
              value: <SECRET_FILE_NAME>
            - name: FILE_HANDLING_URL
              value: <FILE_HANDLING_URL>
            - name: FILE_HANDLING_PORT
              value: <FILE_HANDLING_PORT>
            - name: USER_URL
              value: <USER_URL>
            - name: USER_PORT
              value: <USER_PORT>
            - name: CHALLENGE_URL
              value: <CHALLENGE_URL>
            - name: CHALLENGE_PORT
              value: <CHALLENGE_PORT>
            - name: SOLUTION_URL
              value: http://localhost
            - name: SOLUTION_PORT
              value: "3000"
