
apiVersion: v1
kind: Service
metadata:
  name: solution-service
  namespace: solution
spec:
  selector:
    app: solution
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer