apiVersion: apps/v1
kind: Deployment
metadata:
  name: user
  namespace: user
  labels:
    app: user

spec:
  replicas: 1
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
      namespace: user
    spec:
      serviceAccountName: user
      nodeSelector:
        iam.gke.io/gke-metadata-server-enabled: "true"
      containers:
        - name: user
          image: europe-west4-docker.pkg.dev/codehub-400314/code-hub-main/user:latest
          resources:
            limits:
              cpu: "1"
              memory: "512Mi"
            requests:
              cpu: "500m"
              memory: "256Mi"
          env:
            - name: PROJECT_ID
              value: codehub-400314
            - name: SECRET_FILE_NAME
              value: oxuxxuomhc
            - name: STORAGE_BUCKET_NAME
              value: codehub-public-keys
            - name: PUBLIC_KEY_FILENAME
              value: public_key_YUQWEF7UFJ.pem
            - name: FILE_HANDLING_URL
              value: "http://filehandling-service.filehandling.svc.cluster.local"
            - name: FILE_HANDLING_PORT
              value: 80
            - name: SOLUTION_URL
              value: "http://solution-service.solution.svc.cluster.local"
            - name: SOLUTION_PORT
              value: 80
            - name: CHALLENGE_URL
              value: "http://challenge-service.challenge.svc.cluster.local"
            - name: CHALLENGE_PORT
              value: 80