version: '3'
services:
  builder:
    image: builder:latest
    environment:
      - "FILE_HANDLER_URL=host.docker.internal:3000"
      - "TOKEN=token"
      - "ENTRY_POINT=Solution.java"
      - "SOURCE_FOLDER_NAME=test-solution-source"
      - "EXECUTABLE_FOLDER_NAME=test-solution-executable"
    network_mode: "bridge"